# This is a basic workflow to help you get started with Actions

name: PowerShell

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: before checkout
        run: ls
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: after checkout
        run: |
            cd ps
            pwd
      # Run GetStation
      - name: GetStation
      run:  ./GetStation.ps1 1070061       

      # Unit Test
      - name: Install-Module
        shell: pwsh -File {0}
        run:  |
            Install-Module -Name Pester
            Invoke-Pester
        

      
